### ISSUE TITLE
Pictionary Plugin does not work with MCFunctions

### ISSUE THREAD

**Issue by ZaneWilkerson** [EGO-Minecraft-Events/EdgeGamers-Events#21]
The Pictionary Plugin isn't functional with Pictionary Night yet. 
Please fix

**Comment by Icohedron** [comment]
Aqua's too lazy to use a mcfunction -> command block -> mcfunction setup to work around this issue.
So it'll be a while until this is fixed.

**Comment by Icohedron** [comment]
https://gitlab.com/ego-mc-events/EdgeGamers-Events/issues/7
