### ISSUE TITLE
Pictionary: Topics file on Git repo is publicly visible

### ISSUE THREAD

**Issue by Icohedron** [EGO-Minecraft-Events/EdgeGamers-Events#23]
We should have a way to keep the topics.txt from being publicly visible to anyone.
Options:
1. Encrypt the topics.txt file (whomever adds/changes the topics must know the encryption key and how to encrypt)
2. Make this Git repo private. (Costs money, unless using student perks but that's not a permanent solution. We could move over to [GitLab](www.gitlab.com) for their free private repos, which also comes with other nice perks that let us organize and automate even more things)

**Comment by ZaneWilkerson** [comment]
Okay. For the time being, I can encrypt the file. Then we can decide whether to use git labs or some other solution.

**Comment by Icohedron** [comment]
Ey, even if we are going with solution 1, we still have to talk about how we should encrypt and decrypt it.

**Comment by Icohedron** [comment]
A Python script could be used to encrypt and decrypt the topics file.
[simple-crypt](https://pypi.python.org/pypi/simple-crypt) could be useful.

**Comment by Icohedron** [comment]
https://gitlab.com/ego-mc-events/EdgeGamers-Events/issues/10
